import type { AssetRef } from './asset'
import type { Link } from './link'

/**
 * Opaque component on the core side — typed precisely (Vue Component) at the `@kurvo/vue` level.
 * Intentionally broad to preserve the "no Vue runtime dep in core" boundary.
 */
export type ComponentLike = unknown

export type FieldType =
  | 'text'
  | 'textarea'
  | 'richtext'
  | 'number'
  | 'boolean'
  | 'select'
  | 'image'
  | 'link'
  | 'color'
  | 'custom'

export interface RichTextValue {
  type: 'doc'
  content?: unknown[]
}

export type FieldValidator<V> = (value: V, allProps: Record<string, unknown>) => string | true

interface BaseFieldDefinition<T extends FieldType, V> {
  type: T
  label?: string
  description?: string
  required?: boolean
  default?: V
  validate?: FieldValidator<V>
}

export interface TextFieldDefinition extends BaseFieldDefinition<'text', string> {
  maxLength?: number
  minLength?: number
  placeholder?: string
}

export interface TextareaFieldDefinition extends BaseFieldDefinition<'textarea', string> {
  rows?: number
  maxLength?: number
  minLength?: number
}

export interface RichTextFieldDefinition extends BaseFieldDefinition<'richtext', RichTextValue> {
  marks?: readonly string[]
  nodes?: readonly string[]
}

export interface NumberFieldDefinition extends BaseFieldDefinition<'number', number> {
  min?: number
  max?: number
  step?: number
}

export type BooleanFieldDefinition = BaseFieldDefinition<'boolean', boolean>

export interface SelectFieldOption<V extends string = string> {
  value: V
  label: string | Record<string, string>
}

export interface SelectFieldDefinition<V extends string = string> extends BaseFieldDefinition<
  'select',
  V
> {
  options: ReadonlyArray<SelectFieldOption<V>>
  multiple?: boolean
}

export interface ImageFieldDefinition extends BaseFieldDefinition<'image', AssetRef> {
  accept?: readonly string[]
  maxSize?: number
}

export interface LinkFieldDefinition extends BaseFieldDefinition<'link', Link> {
  allowExternal?: boolean
  allowAnchor?: boolean
  allowAsset?: boolean
}

export interface ColorFieldDefinition extends BaseFieldDefinition<'color', string> {
  preset?: readonly string[]
  allowCustom?: boolean
}

/**
 * One-off custom field (`f.custom<T>({...})`) or one generated by a registered FieldType
 * (`f.register(defineFieldType(...))`).
 *
 * `name` identifies registered types. For a one-off, `name` may be `undefined`.
 */
export interface CustomFieldDefinition<TValue = unknown> extends BaseFieldDefinition<
  'custom',
  TValue
> {
  name?: string
  component: ComponentLike
}

export type FieldDefinition =
  | TextFieldDefinition
  | TextareaFieldDefinition
  | RichTextFieldDefinition
  | NumberFieldDefinition
  | BooleanFieldDefinition
  | SelectFieldDefinition
  | ImageFieldDefinition
  | LinkFieldDefinition
  | ColorFieldDefinition
  | CustomFieldDefinition

/**
 * Runtime value stored in `Block.props[fieldName]`.
 *
 * Custom fields can hold anything (`unknown`), so the union stays open.
 */
export type Field = string | number | boolean | RichTextValue | AssetRef | Link | null | unknown

/**
 * Fluent builder returned by `f.text()`, `f.image()`, etc.
 *
 * The `TValue` parameter reflects the type of the stored value once the field is configured
 * (`f.text()` → `string | undefined`, `.required()` → `string`).
 *
 * The `_build()` method (internal) materializes the final `FieldDefinition`.
 */
export interface FieldBuilder<TValue> {
  required(): FieldBuilder<NonNullable<TValue>>
  default(value: NonNullable<TValue>): FieldBuilder<TValue>
  label(label: string): FieldBuilder<TValue>
  description(description: string): FieldBuilder<TValue>
  validate(fn: FieldValidator<TValue>): FieldBuilder<TValue>
  /** @internal */
  _build(): FieldDefinition
  /** @internal phantom type for inference */
  readonly _value?: TValue
}

/**
 * Definition of a reusable field type, returned by `defineFieldType<TValue>(name, config)`.
 * Once passed to `f.register(...)`, it is accessible via `f.<name>()` typed identically to builtins.
 */
export interface FieldTypeDefinition<TValue> {
  name: string
  component: ComponentLike
  default?: TValue
  validate?: FieldValidator<TValue>
  label?: string
  description?: string
  /** @internal phantom */
  readonly _value?: TValue
}

/**
 * Extracts `TValue` from a `FieldBuilder<TValue>` or a `FieldTypeDefinition<TValue>`.
 * Used by `InferBlockProps<typeof MyBlock>`.
 */
export type InferFieldValue<F> =
  F extends FieldBuilder<infer V> ? V : F extends FieldTypeDefinition<infer V> ? V : unknown
